# Site wide configuration

title: "কৃত্রিম বুদ্ধিমত্তা | বাংলা"
description: "বাংলাদেশে মেশিন লার্নিং কাজ"
logo: 120x120.gif
teaser: 400x250.gif
locale: bn_BD

# locale: en_US
url: "https://r-hassan.github.io"
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: "Rakibul Hassan"
  web: "https://mademistakes.com"
  twitter: "raqueeb"
  bio: "Just another boring, tattooed, time traveling designer."
  avatar: "bio-photo.jpg" # 160x160 px image for author byline
  google:
    plus: "+MichaelRoseDesign"
    ad-client: "ca-pub-7328585512091257"
    ad-slot: 3049671934
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
